/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as CreateRouteImport } from './routes/create'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as RankRouteImport } from './routes/rank'
import { Route as RequestCollegeRouteImport } from './routes/request-college'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCollegeRoute = RequestCollegeRouteImport.update({
  id: '/request-college',
  path: '/request-college',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/create': typeof CreateRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/pulse': typeof PulseRoute
  '/rank': typeof RankRoute
  '/request-college': typeof RequestCollegeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/create': typeof CreateRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/pulse': typeof PulseRoute
  '/rank': typeof RankRoute
  '/request-college': typeof RequestCollegeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/create': typeof CreateRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/pulse': typeof PulseRoute
  '/rank': typeof RankRoute
  '/request-college': typeof RequestCollegeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campus'
    | '/create'
    | '/home'
    | '/profile'
    | '/pulse'
    | '/rank'
    | '/request-college'
    | '/reset-password'
    | '/auth/forgot'
    | '/auth/verify'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campus'
    | '/create'
    | '/home'
    | '/profile'
    | '/pulse'
    | '/rank'
    | '/request-college'
    | '/reset-password'
    | '/auth/forgot'
    | '/auth/verify'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/campus'
    | '/create'
    | '/home'
    | '/profile'
    | '/pulse'
    | '/rank'
    | '/request-college'
    | '/reset-password'
    | '/auth/forgot'
    | '/auth/verify'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampusRoute: typeof CampusRoute
  CreateRoute: typeof CreateRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  PulseRoute: typeof PulseRoute
  RankRoute: typeof RankRoute
  RequestCollegeRoute: typeof RequestCollegeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-college': {
      id: '/request-college'
      path: '/request-college'
      fullPath: '/request-college'
      preLoaderRoute: typeof RequestCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampusRoute: CampusRoute,
  CreateRoute: CreateRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  PulseRoute: PulseRoute,
  RankRoute: RankRoute,
  RequestCollegeRoute: RequestCollegeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
